// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdannmjpkhwcjjpwomrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkYW5ubWpwa2h3Y2pqcHdvbXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTg4NzQsImV4cCI6MjA2MzkzNDg3NH0.Pf4eKkIiHx305Q27YGvGXrBA7GMLkk2oFVKBbxEIquA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);